server:
  port: 8080 #端口号，默认是8080
  servlet:
    context-path: / #上下文路径，默认是/
#连接数据库的四个必要参数，其他数据源参数有默认值
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pethome?useUnicode=true&characterEncoding=utf8
  redis:
    host: 127.0.0.1 #连接redis的主机ip
    port: 6379
    timeout: 5000 #连接超时 毫秒
#    password: 123456
    jedis:
      pool:
        maxActive: 30 #给定时间可以分配的最大连接数。 使用负值表示没有限制
        maxIdle: 30  #最大空闲连接数
        minIdle: 10 # 最小空间连接数
        maxWait: -1 #连接池最大等待时间 -1没有限制
#配置别名 和扫描mapper文件【约定大于配置】
mybatis:
  type-aliases-package: com.sgfy.org.domain,com.sgfy.org.query
  configuration:
    map-underscore-to-camel-case: true
#配置日志等级
logging:
  level:
    cn.itsource: debug
